# Generated by Django 5.1.6 on 2025-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='max_patients',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
